/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atlan1_mctpo_mobile_GameActivity */

#ifndef _Included_com_atlan1_mctpo_mobile_GameActivity
#define _Included_com_atlan1_mctpo_mobile_GameActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_PRIVATE
#define com_atlan1_mctpo_mobile_GameActivity_MODE_PRIVATE 0L
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_WORLD_READABLE
#define com_atlan1_mctpo_mobile_GameActivity_MODE_WORLD_READABLE 1L
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_WORLD_WRITEABLE
#define com_atlan1_mctpo_mobile_GameActivity_MODE_WORLD_WRITEABLE 2L
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_APPEND
#define com_atlan1_mctpo_mobile_GameActivity_MODE_APPEND 32768L
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_MULTI_PROCESS
#define com_atlan1_mctpo_mobile_GameActivity_MODE_MULTI_PROCESS 4L
#undef com_atlan1_mctpo_mobile_GameActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_atlan1_mctpo_mobile_GameActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_AUTO_CREATE
#define com_atlan1_mctpo_mobile_GameActivity_BIND_AUTO_CREATE 1L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_DEBUG_UNBIND
#define com_atlan1_mctpo_mobile_GameActivity_BIND_DEBUG_UNBIND 2L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_NOT_FOREGROUND
#define com_atlan1_mctpo_mobile_GameActivity_BIND_NOT_FOREGROUND 4L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_ABOVE_CLIENT
#define com_atlan1_mctpo_mobile_GameActivity_BIND_ABOVE_CLIENT 8L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_atlan1_mctpo_mobile_GameActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_WAIVE_PRIORITY
#define com_atlan1_mctpo_mobile_GameActivity_BIND_WAIVE_PRIORITY 32L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_IMPORTANT
#define com_atlan1_mctpo_mobile_GameActivity_BIND_IMPORTANT 64L
#undef com_atlan1_mctpo_mobile_GameActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_atlan1_mctpo_mobile_GameActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_atlan1_mctpo_mobile_GameActivity_CONTEXT_INCLUDE_CODE
#define com_atlan1_mctpo_mobile_GameActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_atlan1_mctpo_mobile_GameActivity_CONTEXT_IGNORE_SECURITY
#define com_atlan1_mctpo_mobile_GameActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_atlan1_mctpo_mobile_GameActivity_CONTEXT_RESTRICTED
#define com_atlan1_mctpo_mobile_GameActivity_CONTEXT_RESTRICTED 4L
#undef com_atlan1_mctpo_mobile_GameActivity_RESULT_CANCELED
#define com_atlan1_mctpo_mobile_GameActivity_RESULT_CANCELED 0L
#undef com_atlan1_mctpo_mobile_GameActivity_RESULT_OK
#define com_atlan1_mctpo_mobile_GameActivity_RESULT_OK -1L
#undef com_atlan1_mctpo_mobile_GameActivity_RESULT_FIRST_USER
#define com_atlan1_mctpo_mobile_GameActivity_RESULT_FIRST_USER 1L
#undef com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_DISABLE
#define com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_DIALER
#define com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_DIALER 1L
#undef com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SHORTCUT
#define com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_atlan1_mctpo_mobile_GameActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_atlan1_mctpo_mobile_GameActivity_tzmonUse
#define com_atlan1_mctpo_mobile_GameActivity_tzmonUse 1L
#undef com_atlan1_mctpo_mobile_GameActivity_initFlag
#define com_atlan1_mctpo_mobile_GameActivity_initFlag 0L
/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonHello
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonInitKeyNFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonInitKeyNFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonCheckAppHash
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonCheckAppHash
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonSecureUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonSecureUpdate
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonAbusingDetection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonAbusingDetection
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonSyncTimer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonSyncTimer
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonHidingSetup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonHidingSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_atlan1_mctpo_mobile_GameActivity
 * Method:    tzmonGetHKey
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_atlan1_mctpo_mobile_GameActivity_tzmonGetHKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
