/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kaushal_game_MainActivity */

#ifndef _Included_com_example_kaushal_game_MainActivity
#define _Included_com_example_kaushal_game_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_kaushal_game_MainActivity_BIND_ABOVE_CLIENT
#define com_example_kaushal_game_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_example_kaushal_game_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_example_kaushal_game_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_example_kaushal_game_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_example_kaushal_game_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_example_kaushal_game_MainActivity_BIND_AUTO_CREATE
#define com_example_kaushal_game_MainActivity_BIND_AUTO_CREATE 1L
#undef com_example_kaushal_game_MainActivity_BIND_DEBUG_UNBIND
#define com_example_kaushal_game_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_example_kaushal_game_MainActivity_BIND_EXTERNAL_SERVICE
#define com_example_kaushal_game_MainActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef com_example_kaushal_game_MainActivity_BIND_IMPORTANT
#define com_example_kaushal_game_MainActivity_BIND_IMPORTANT 64L
#undef com_example_kaushal_game_MainActivity_BIND_NOT_FOREGROUND
#define com_example_kaushal_game_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_example_kaushal_game_MainActivity_BIND_WAIVE_PRIORITY
#define com_example_kaushal_game_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_example_kaushal_game_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_example_kaushal_game_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_example_kaushal_game_MainActivity_CONTEXT_INCLUDE_CODE
#define com_example_kaushal_game_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_example_kaushal_game_MainActivity_CONTEXT_RESTRICTED
#define com_example_kaushal_game_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_example_kaushal_game_MainActivity_MODE_APPEND
#define com_example_kaushal_game_MainActivity_MODE_APPEND 32768L
#undef com_example_kaushal_game_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_example_kaushal_game_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_example_kaushal_game_MainActivity_MODE_MULTI_PROCESS
#define com_example_kaushal_game_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_example_kaushal_game_MainActivity_MODE_NO_LOCALIZED_COLLATORS
#define com_example_kaushal_game_MainActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef com_example_kaushal_game_MainActivity_MODE_PRIVATE
#define com_example_kaushal_game_MainActivity_MODE_PRIVATE 0L
#undef com_example_kaushal_game_MainActivity_MODE_WORLD_READABLE
#define com_example_kaushal_game_MainActivity_MODE_WORLD_READABLE 1L
#undef com_example_kaushal_game_MainActivity_MODE_WORLD_WRITEABLE
#define com_example_kaushal_game_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_example_kaushal_game_MainActivity_DEFAULT_KEYS_DIALER
#define com_example_kaushal_game_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_example_kaushal_game_MainActivity_DEFAULT_KEYS_DISABLE
#define com_example_kaushal_game_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_example_kaushal_game_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_example_kaushal_game_MainActivity_RESULT_CANCELED
#define com_example_kaushal_game_MainActivity_RESULT_CANCELED 0L
#undef com_example_kaushal_game_MainActivity_RESULT_FIRST_USER
#define com_example_kaushal_game_MainActivity_RESULT_FIRST_USER 1L
#undef com_example_kaushal_game_MainActivity_RESULT_OK
#define com_example_kaushal_game_MainActivity_RESULT_OK -1L
#undef com_example_kaushal_game_MainActivity_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS
#define com_example_kaushal_game_MainActivity_MAX_NUM_PENDING_FRAGMENT_ACTIVITY_RESULTS 65534L
#undef com_example_kaushal_game_MainActivity_MSG_REALLY_STOPPED
#define com_example_kaushal_game_MainActivity_MSG_REALLY_STOPPED 1L
#undef com_example_kaushal_game_MainActivity_MSG_RESUME_PENDING
#define com_example_kaushal_game_MainActivity_MSG_RESUME_PENDING 2L
#undef com_example_kaushal_game_MainActivity_tzmonUse
#define com_example_kaushal_game_MainActivity_tzmonUse 1L

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonInitKeyNFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonInitKeyNFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonCheckAppHash
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonCheckAppHash
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonSecureUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonSecureUpdate
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonAbusingDetection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonAbusingDetection
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonSyncTimer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonSyncTimer
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonHidingSetup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_kaushal_game_MainActivity_tzmonHidingSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_example_kaushal_game_MainActivity
 * Method:    tzmonGetHKey
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_kaushal_game_MainActivity_tzmonGetHKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
