/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_blockinger2_game_components_GameState */

#ifndef _Included_org_blockinger2_game_components_GameState
#define _Included_org_blockinger2_game_components_GameState
#ifdef __cplusplus
extern "C" {
#endif
#undef org_blockinger2_game_components_GameState_STATE_STARTABLE
#define org_blockinger2_game_components_GameState_STATE_STARTABLE 0L
#undef org_blockinger2_game_components_GameState_STATE_RUNNING
#define org_blockinger2_game_components_GameState_STATE_RUNNING 1L
#undef org_blockinger2_game_components_GameState_STATE_PAUSED
#define org_blockinger2_game_components_GameState_STATE_PAUSED 2L
#undef org_blockinger2_game_components_GameState_STATE_FINISHED
#define org_blockinger2_game_components_GameState_STATE_FINISHED 3L
/*
 * Class:     org_blockinger2_game_components_GameState
 * Method:    jniHidingKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_blockinger2_game_components_GameState_tzmonHKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
