/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_gamelearn_Main */

#ifndef _Included_com_learn_gamelearn_Main
#define _Included_com_learn_gamelearn_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef com_learn_gamelearn_Main_MODE_PRIVATE
#define com_learn_gamelearn_Main_MODE_PRIVATE 0L
#undef com_learn_gamelearn_Main_MODE_WORLD_READABLE
#define com_learn_gamelearn_Main_MODE_WORLD_READABLE 1L
#undef com_learn_gamelearn_Main_MODE_WORLD_WRITEABLE
#define com_learn_gamelearn_Main_MODE_WORLD_WRITEABLE 2L
#undef com_learn_gamelearn_Main_MODE_APPEND
#define com_learn_gamelearn_Main_MODE_APPEND 32768L
#undef com_learn_gamelearn_Main_MODE_MULTI_PROCESS
#define com_learn_gamelearn_Main_MODE_MULTI_PROCESS 4L
#undef com_learn_gamelearn_Main_BIND_AUTO_CREATE
#define com_learn_gamelearn_Main_BIND_AUTO_CREATE 1L
#undef com_learn_gamelearn_Main_BIND_DEBUG_UNBIND
#define com_learn_gamelearn_Main_BIND_DEBUG_UNBIND 2L
#undef com_learn_gamelearn_Main_BIND_NOT_FOREGROUND
#define com_learn_gamelearn_Main_BIND_NOT_FOREGROUND 4L
#undef com_learn_gamelearn_Main_BIND_ABOVE_CLIENT
#define com_learn_gamelearn_Main_BIND_ABOVE_CLIENT 8L
#undef com_learn_gamelearn_Main_BIND_ALLOW_OOM_MANAGEMENT
#define com_learn_gamelearn_Main_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_learn_gamelearn_Main_BIND_WAIVE_PRIORITY
#define com_learn_gamelearn_Main_BIND_WAIVE_PRIORITY 32L
#undef com_learn_gamelearn_Main_BIND_IMPORTANT
#define com_learn_gamelearn_Main_BIND_IMPORTANT 64L
#undef com_learn_gamelearn_Main_BIND_ADJUST_WITH_ACTIVITY
#define com_learn_gamelearn_Main_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_learn_gamelearn_Main_CONTEXT_INCLUDE_CODE
#define com_learn_gamelearn_Main_CONTEXT_INCLUDE_CODE 1L
#undef com_learn_gamelearn_Main_CONTEXT_IGNORE_SECURITY
#define com_learn_gamelearn_Main_CONTEXT_IGNORE_SECURITY 2L
#undef com_learn_gamelearn_Main_CONTEXT_RESTRICTED
#define com_learn_gamelearn_Main_CONTEXT_RESTRICTED 4L
#undef com_learn_gamelearn_Main_RESULT_CANCELED
#define com_learn_gamelearn_Main_RESULT_CANCELED 0L
#undef com_learn_gamelearn_Main_RESULT_OK
#define com_learn_gamelearn_Main_RESULT_OK -1L
#undef com_learn_gamelearn_Main_RESULT_FIRST_USER
#define com_learn_gamelearn_Main_RESULT_FIRST_USER 1L
#undef com_learn_gamelearn_Main_DEFAULT_KEYS_DISABLE
#define com_learn_gamelearn_Main_DEFAULT_KEYS_DISABLE 0L
#undef com_learn_gamelearn_Main_DEFAULT_KEYS_DIALER
#define com_learn_gamelearn_Main_DEFAULT_KEYS_DIALER 1L
#undef com_learn_gamelearn_Main_DEFAULT_KEYS_SHORTCUT
#define com_learn_gamelearn_Main_DEFAULT_KEYS_SHORTCUT 2L
#undef com_learn_gamelearn_Main_DEFAULT_KEYS_SEARCH_LOCAL
#define com_learn_gamelearn_Main_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_learn_gamelearn_Main_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_learn_gamelearn_Main_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_learn_gamelearn_Main_tzmonUse
#define com_learn_gamelearn_Main_tzmonUse 1L
/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_learn_gamelearn_Main_tzmonHello
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonInitKeyNFlag
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonInitKeyNFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonCheckAppHash
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonCheckAppHash
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonSecureUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonSecureUpdate
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonAbusingDetection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonAbusingDetection
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonSyncTimer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonSyncTimer
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonHidingSetup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_learn_gamelearn_Main_tzmonHidingSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_learn_gamelearn_Main
 * Method:    tzmonGetHKey
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_learn_gamelearn_Main_tzmonGetHKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
